/* test/sourcemaps/samples/static-no-script/input.svelte generated by Svelte vx.xx.x */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "svelte/internal";

function create_fragment(ctx) {
	let p;

	return {
		c() {
			p = element("p");
			p.textContent = "no moving parts";
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

class Input extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Input;
//# sourceMappingURL=output.js.map