/* test/sourcemaps/samples/css/input.svelte generated by Svelte vx.xx.x */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "svelte/internal";

function add_css() {
	var style = element("style");
	style.id = "svelte-sg04hs-style";
	style.textContent = ".foo.svelte-sg04hs{color:red}";
	append(document.head, style);
}

function create_fragment(ctx) {
	let p;

	return {
		c() {
			p = element("p");
			p.textContent = "red";
			attr(p, "class", "foo svelte-sg04hs");
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

class Input extends SvelteComponent {
	constructor(options) {
		super();
		if (!document.getElementById("svelte-sg04hs-style")) add_css();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Input;
//# sourceMappingURL=output.js.map